version: '3.1'

services:

  mode-base:
    build:
      context: .
      dockerfile: node_gyp_for_dev.Dockerfile
    image: ptrn2l2/node_gyp_for_dev:8.9-alpine
    entrypoint: node
    command: -v
    volumes:
      -  .:/workdir
      - npm_gyp_for_dev_vol:/workdir/node_modules
    environment:
      - NODE_ENV=development

  npm-install-modules:
    build:
      context: .
      dockerfile: npm_gyp_for_dev.Dockerfile
    image: ptrn2l2/npm_gyp_for_dev:8.9-alpine
    entrypoint: npm
    command: install
    volumes:
      -  .:/workdir
      - npm_gyp_for_dev_vol:/workdir/node_modules
    depends_on:
      - mode-base
    environment:
      - NODE_ENV=development

  webpack-dev-server:
    build:
      context: .
      dockerfile: webpack_gyp_for_dev.Dockerfile
    image: ptrn2l2/webpack_gyp_for_dev:8.9-alpine
    volumes:
      -  .:/workdir
      - npm_gyp_for_dev_vol:/workdir/node_modules
    depends_on:
      - npm-install-modules
    environment:
      - NODE_ENV=development
      - WEBPACK_DEV_SERVER_PORT=44297
      - WEBPACKCONFIG=webpack.config.js

volumes: 
  npm_gyp_for_dev_vol: {}